### ISSUE TITLE
imports-formatter 在 Dubbo-go 3.0 分支运行时报错

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [dubbogo/tools#3]
1. 注释导致的错误
```
$ imports-formatter -module dubbo.apache.org/dubbo-go/v3
panic: unexpected import format: * <a href="http://en.wikipedia.org/wiki/Failback">Failback</a> in file /Users/laurence/Desktop/workplace/dubbogo/dubbo-go/cluster/cluster_impl/failback_cluster_invoker.go

goroutine 1 [running]:
main.main()
        /Users/laurence/go/pkg/mod/github.com/dubbogo/tools@v0.0.0-20210717033822-e84883e79e10/cmd/imports-formatter/main.go:75 +0x18c
laurence@B-V9HYQ05P-1223 dubbo-go % imports-formatter -module dubbo.apache.org/dubbo-go/v3
panic: unexpected import format: * <a href="http://en.wikipedia.org/wiki/Fail-safe">Fail-safe</a> in file /Users/laurence/Desktop/workplace/dubbogo/dubbo-go/cluster/cluster_impl/failsafe_cluster_invoker.go

goroutine 1 [running]:
main.main()
        /Users/laurence/go/pkg/mod/github.com/dubbogo/tools@v0.0.0-20210717033822-e84883e79e10/cmd/imports-formatter/main.go:75 +0x18c
l
```

2. 单个 import block 为什么会增加空行？
我认为单个import block内不需要增加任何空行。单个import block 内条目的顺序这个工具无需关心。开发者最终需要执行 go fmt project来保证条目顺序正确。这个工具只关心3 block 拆分。
@Mulavar

**Comment by Mulavar** [comment]
第二点是指希望import block里没有空行？
这个其实是一开始的时候希望的实现方式是第二个block，也就是第三方的import block，如果有多个第三方，就用空行做下分隔。
提到的关于排序都好改，但可能一开始没有沟通到这个工具需要的样子，所以做了些额外的事…

**Comment by Mulavar** [comment]
另外关于第一点注释错误，其实现在没找到好的方法去检测一个import的开始和结束（用括号的话注释里也会出现，无法识别单行）…所以目前几乎都是增加分支的方式去判断有注释等特殊情况，目前已在修。

**Comment by LaurenceLiZhixin** [comment]
![图片](https://user-images.githubusercontent.com/45508533/128972910-4cbae629-9b7e-47fb-871c-de63a0484016.png)

对于没有import的文件，会新增一些莫名其妙的注释。 @Mulavar

**Comment by Mulavar** [comment]
收到，抽空排查下。
